version: "3.8"
services:
  api:
    image: "api:latest"
    container_name: "slack-api"
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "api:latest"
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - slack_api
  nginx:
    image: "nginx"
    container_name: "nginx"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - slack_api

networks:
  slack_api:
    driver: bridge
