name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          ssh-key: ${{ secrets.REPO_SSH_KEY }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git docker-compose

      - name: SSH into EC2 and pull the latest code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ -d "wordcab-slack" ]; then
              (cd wordcab-slack && git pull)
            else
              (git clone --depth 1 git@github.com:Wordcab/wordcab-slack.git wordcab-slack && cd wordcab-slack && git checkout main)
            fi
            touch .env
            echo "WORDCAB_API_KEY=${{ secrets.WORDCAB_API_KEY }}" >> .env
            echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> .env
            echo "SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}" >> .env
            sudo docker-compose build
            sudo docker-compose up -d
